name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  hello_world_jobs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello World
        run: echo "Hello World!"

      - name: print current date
        run: date
       
      - name: current directory content
        run: ls -l  